module.exports = {
  releaseNotes: [
    "release-notes/README",
    {
      type: 'category',
      label: 'Middleware',
      items: [
        'release-notes/middleware/middleware-1.3.33',
        'release-notes/middleware/middleware-1.3.32',
        'release-notes/middleware/middleware-1.3.31',
        'release-notes/middleware/middleware-1.3.30',
        'release-notes/middleware/middleware-1.3.29',
        'release-notes/middleware/middleware-1.3.28',
        'release-notes/middleware/middleware-1.3.27',
        'release-notes/middleware/middleware-1.3.26',
        'release-notes/middleware/middleware-1.3.25',
        'release-notes/middleware/middleware-1.3.24',
        'release-notes/middleware/middleware-1.3.23',
        'release-notes/middleware/middleware-1.3.22',
        'release-notes/middleware/middleware-1.3.21',
        'release-notes/middleware/middleware-1.3.20',
        'release-notes/middleware/middleware-1.3.19',
        'release-notes/middleware/middleware-1.3.18',
        'release-notes/middleware/middleware-1.3.17',
        'release-notes/middleware/middleware-1.3.16',
        'release-notes/middleware/middleware-1.3.15',
        'release-notes/middleware/middleware-1.3.14',
        'release-notes/middleware/middleware-1.3.13',
        'release-notes/middleware/middleware-1.3.12',
        'release-notes/middleware/middleware-1.3.11',
        'release-notes/middleware/middleware-1.3.10',
        'release-notes/middleware/middleware-1.3.9',
        'release-notes/middleware/middleware-1.3.8',
        'release-notes/middleware/middleware-1.3.7',
        'release-notes/middleware/middleware-1.3.6',
        'release-notes/middleware/middleware-1.3.5',
        'release-notes/middleware/middleware-1.3.4',
        'release-notes/middleware/middleware-1.3.3',
        'release-notes/middleware/middleware-1.3.2',
        'release-notes/middleware/middleware-1.3.1'
      ]
    },
    {
      type: 'category',
      label: 'Portal',
      items: [
        'release-notes/portal/portal-sprint-111',
        'release-notes/portal/portal-sprint-110',
        'release-notes/portal/portal-sprint-109',
        'release-notes/portal/portal-sprint-108',
        'release-notes/portal/portal-sprint-107',
        'release-notes/portal/portal-sprint-106',
        'release-notes/portal/portal-sprint-105',
        'release-notes/portal/portal-sprint-104',
        'release-notes/portal/portal-sprint-103',
        'release-notes/portal/portal-sprint-102',
        'release-notes/portal/portal-sprint-101',
        'release-notes/portal/portal-sprint-100',
        'release-notes/portal/portal-sprint-99',
        'release-notes/portal/portal-sprint-98',
        'release-notes/portal/portal-sprint-97',
        'release-notes/portal/portal-sprint-96',
        'release-notes/portal/portal-sprint-95',
        'release-notes/portal/portal-sprint-94',
        'release-notes/portal/portal-sprint-93',
        'release-notes/portal/portal-sprint-92',
        'release-notes/portal/portal-sprint-91',
        'release-notes/portal/portal-sprint-90',
        'release-notes/portal/portal-sprint-89',
        'release-notes/portal/portal-sprint-88',
        'release-notes/portal/portal-sprint-87',        
        'release-notes/portal/portal-sprint-86',
        'release-notes/portal/portal-sprint-85',
        'release-notes/portal/portal-sprint-84',
        'release-notes/portal/portal-sprint-83',
        'release-notes/portal/portal-sprint-82',
        'release-notes/portal/portal-sprint-81',
        'release-notes/portal/portal-sprint-80',
        'release-notes/portal/portal-sprint-79',
        'release-notes/portal/portal-sprint-78',
        'release-notes/portal/portal-sprint-77',
        'release-notes/portal/portal-sprint-76',
        'release-notes/portal/portal-sprint-75'
      ]
    }
  ]
}
