name: Check Links

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          args: --error --quiet --no-progress

      - name: Comment Broken Links
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: lychee/out.md

      - name: Fail if broken links found
        if: steps.lychee.outcome == 'failure'
        run: exit 1
